server:
  port: 2021

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:../test
    username: danplay

  h2:
    console:
      enabled: true
      path: /h2-console

  redis:
    host: localhost
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: HongdeokKim.test
    password: 1q2w3e4rtnthd!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
